name: update Stundenplan Daten
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '51 11 * * *'
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python run.py
