name: Image Name Updater

on:
  push:
    branches: 
      - "master"
    paths: 
      - 'Images/**/**.png'
    
  workflow_dispatch:
      
jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Rename Images
        continue-on-error: true
        run: mv ./Images/Fenster_Links/*.png ./Images/Fenster_Links/Image.png
      
      - name: Push to GitHub
        run: |
          git checkout master
          git config --global user.email "paul.warta@icloud.com"
          git config --global user.name "Paul Warta"
          git add .
          git commit -m "Renamed files in ./Images/*/*.png to ./Images/*/Image.png" -a
          git status
          git push
